class AddNewProductPage:
    settingBtn = "//button[@id='product-editor-settings']"
    saveBtn = "//button[@name='save']"
    saveContEditBtn = "//button[@name='save-continue']"
    toggle = "//label[@class='onoffswitch-label']"
    giftCard = "//div[@class='card-title' and text()='Gift card']"
    rentalCard = "//div[@class='card-title' and text()='Rental']"
    downloadableProductCard = "//div[@class='card-title' and text()='Downloadable product']"
    txtProductName = "//input[@id='Name']"
    txtShortDescription = "//textarea[@id='ShortDescription']"
    txtPrice = "div#product-price div#product-price-area input"
    taxExemptCheckbox = "//div[@id='product-price']//input[@id='IsTaxExempt']"
    shipCheckbox = "//div[@id='product-shipping']//input[@id='IsShipEnabled']"
    shipWeight = "div#product-shipping input#Weight"
    shipLength = "div#product-shipping input#Length"
    shipWidth = "div#product-shipping input#Width"
    shipHeight = "div#product-shipping input#Height"
    inventoryMethod = "//div[@id='product-inventory']//select[@id='ManageInventoryMethodId']"
    addNewProductSuccessNoti = "//div[@class='alert alert-success alert-dismissable']"