class AddNewProductPage:
    settingBtn = "//button[@id='product-editor-settings']"
    saveBtn = "//button[@name='save']"
    saveContEditBtn = "//button[@name='save-continue']"
    toggle = "//label[@class='onoffswitch-label']"
    giftCard = "//div[@class='card-title' and text()='Gift card']"
    rentalCard = "//div[@class='card-title' and text()='Rental']"
    downloadableProductCard = "//div[@class='card-title' and text()='Downloadable product']"
    txtProductName = "//input[@id='Name']"
    txtShortDescription = "//textarea[@id='ShortDescription']"
    SKU = "//input[@id='Sku']"
    txtPrice = "div#product-price div#product-price-area input:nth-child(2)"
    taxExemptCheckbox = "//div[@id='product-price']//input[@id='IsTaxExempt']"
    shipCheckbox = "//div[@id='product-shipping']//input[@id='IsShipEnabled']"
    shipWeight = "div#product-shipping input#Weight:nth-child(2)"
    shipLength = "div#product-shipping input#Length:nth-child(2)"
    shipWidth = "div#product-shipping input#Width:nth-child(2)"
    shipHeight = "div#product-shipping input#Height:nth-child(2)"
    uploadAvatarButton = "//input[@name='qqfile']"
    uploadAvatarSuccess = "//li[contains(@class,'qq-upload-success')]"
    inventoryMethod = "//div[@id='product-inventory']//select[@id='ManageInventoryMethodId']"
    inventoryMethodSelected = "//div[@id='product-inventory']//select[@id='ManageInventoryMethodId']//option[@selected='selected']"
    addNewProductSuccessNoti = "//div[@class='alert alert-success alert-dismissable']"